tasks:
  - name: Workspace
    init: |
      pnpm add -g pnpm
      pnpm install
      gp sync-done setup
  - name: Server
    init: |
      gp sync-await setup
    command: |
      pnpm --filter @l3s/server start
  - name: Client
    init: |
      gp sync-await setup
    command: |
      gp env REACT_APP_WS_BASE=$(gp url 4000)
      eval $(gp env -e)
      pnpm --filter @l3s/client start

ports:
  - port: 3000
    onOpen: open-browser
  - port: 4000
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - redhat.vscode-yaml
